### PR TITLE
added csv import feature (-f <csvFile>)

### PR DESCRIPTION
**Pull request by dwrightco1**
Added new installer flag: -f <csvFile> 
The README.me has been updated to includes sample CSV.

### CODE REVIEW

**Comment by dwrightco1** [comment]
--- Sample CSV ---
hostname,username,key,ip,dhcp,snat,glance,glance-public,nic1,nic2,mgmtvlan,mgmtip,mgmtnetmask,Storagevlan,storageip,storagenetmask,tunnelvlan,tunnelip,tunnelnetmask
fake01,centos,~/cm-master,172.16.7.182,TRUE,TRUE,TRUE,TRUE,ens160,,243,172.16.243.11,255.255.255.0,244,172.16.244.11,255.255.255.0,245,172.16.245.11,255.255.255.0
fake02,ubuntu,~/cm-master,172.16.7.47,TRUE,FALSE,FALSE,FALSE,ens192,,243,172.16.243.12,255.255.255.0,244,172.16.244.12,255.255.255.0,245,172.16.245.12,255.255.255.0

**Comment by dwrightco1** [comment]
added '-f <tag[,<tag>]>' option for filtering which role(s) are run

**Comment by dwrightco1** [comment]
# ./pf9-express -b -t live-migration,image-import -a hypervisors

# ./pf9-express -b -t deauth -a hypervisors
ASSERT : invalid tag : 'deauth'

**Comment by mmccarre** [comment]
LGTM

**Pull request merged**
