### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by h00pz**
just installed this branch onto RHEL 7.4.  Ansible logs attached.
[tmux-buf.txt](https://github.com/platform9/express/files/2849260/tmux-buf.txt)

### CODE REVIEW

**Comment by jb4free** [comment]
Can one of the admins verify this patch?

**Comment by mmccarre** [comment]
@h00pz there are two pull requests already open for these changes. I would suggest we approve those and merge them instead of creating a new one.

**Comment by h00pz** [comment]
ok Matt.  I will close this PR and approve the others.

**Comment by h00pz** [comment]
run tests

**Comment by mmccarre** [comment]
Closing pull request since it duplicates changes already merged to master.

**Pull request closed without merging**
