### PR TITLE
replace ctrl_ip with du_fqdn for calling management plane APIs

### PR DESCRIPTION
**Pull request by jb4free**
I haven't had a chance to validate this yet, but I wanted it in somebody's hands in case they have a setup they can check on ASAP.

### CODE REVIEW

**Comment by mmccarre** [comment]
It might be helpful to look at the last pull requests where we considered changing this while fixing multi-region support.
- https://github.com/platform9/express/pull/241
- https://github.com/platform9/express/pull/233

**Comment by mmccarre** [comment]
Related to issue #247

**Comment by pshanbhag** [comment]
> I fairly confident w/o additional changes this will break multi-region support. You will want to look at tmp_ip=$(ping -c 1 ${region_url} | grep PING | cut -d ' ' -f3) and ctrl_ip=${tmp_ip:1:((${#tmp_ip}-2))} in the pf9-express bash script
Makes me feel the Ansible goodness should be kept only for the host level stuff and the DU API operations should move into a different place or become Ansible modules (self contained using APIs for qbert and resmgr) themselves.

**Comment by jb4free** [comment]
> > I fairly confident w/o additional changes this will break multi-region support. You will want to look at tmp_ip=$(ping -c 1 ${region_url} | grep PING | cut -d ' ' -f3) and ctrl_ip=${tmp_ip:1:((${#tmp_ip}-2))} in the pf9-express bash script
> 
> Makes me feel the Ansible goodness should be kept only for the host level stuff and the DU API operations should move into a different place or become Ansible modules (self contained using APIs for qbert and resmgr) themselves.

all of this should move to express-cli

**Pull request merged**
