### PR TITLE
Add a playbook to convert inventory names from hyphens to underscores…

### PR DESCRIPTION
**Pull request by busterswt**
… for Ansible 2.8+ (for Issue #210)

### CODE REVIEW

**Comment by busterswt** [comment]
Used this script to update a sample hosts file. Below is the diff:

pf-0108:express jdenton$ diff inventory/hosts inventory/hosts.example
5,6c5,6
< k8s_master
< k8s_worker
---
> k8s-master
> k8s-worker
11c11
< [k8s_master]
---
> [k8s-master]
16c16
< [k8s_worker]
---
> [k8s-worker]

This should first grab matching group names, then match groups and group references (children) accordingly. Makes a backup just incase.

**Comment by busterswt** [comment]
@mmccarre @joshkelly Please let me know what you think.

**Comment by mmccarre** [comment]
@busterswt this is great! It would probably be best to have this run every time express runs.

Some questions/thought I have...
- could we only have it take a backup if dashes are found?
- we should include the downstream changes to invoke this in express, the updates to the default inventory file we provide, readme, etc.

**Comment by busterswt** [comment]
> * could we only have it take a backup if dashes are found?

Yes - I considered doing this, but wanted feedback first. I'll make this change.

> * we should include the downstream changes to invoke this in express, the updates to the default inventory file we provide, readme, etc.

Are you thinking of automatically triggering this change via Express, or simply updating the README to notify the user that this needs to happen prior to running Express? If the former, should there be a flag to trigger this change? Or, would it be better to update Express so that it bails if there are hyphens and have the user run it?

**Comment by mmccarre** [comment]
We could note lib/hosts.tpl which is the template that express copies today into inventory/hosts when the -i option is invoked.

**Comment by jb4free** [comment]
Can one of the admins verify this patch?

**Comment by busterswt** [comment]
@mmccarre Appreciate your feedback when you have time.

**Comment by busterswt** [comment]
> Looks good to me, approving with the assumption that your testing has been successful.

Testing using a broken (underscore) and good (hyphen) inventory were successful. The underscored inventory gets converted, then hyphenated inventory is ignored. If it's a mix, it will get converted, too.

**Comment by mmccarre** [comment]
👍 please squash & merge when you are ready to do so.

**Pull request merged**
